services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: chat_app
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysql -h localhost -u root -p password -e "quit"
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - ./backend/vendor/bundle:/usr/local/bundle
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql2://root:password@db:3306/chat_app
      - RAILS_ENV=development
      - RAILS_MAX_THREADS=5
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails db:create db:migrate && bundle exec rails s -p 8080 -b '0.0.0.0'"
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend

volumes:
  mysql_data:
